// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Hive5
{
	public static class Hive5Config
	{
        //public static string AppKey = "8478cf3d-e563-4c22-a89e-d208c0680b56";	//카톡 검수.
		public static string AppKey = "05ca46a9-323d-4848-aafa-18d4abd50fab";	//개발.
		public static string XPlatformKey 	= "4b9ea368-2809-4e57-91a1-d9ce7ac39534"; // If you need it, request us 
		public static string CustomAccountPlatformName = "Hive5"; 
        
    	public static string ProductionHost	= "https://tbahjakv.api.hive5.io";
		public static string BetaHost 		= "https://beta.hornet.hive5.io";
        public static string AlphaHost      = "https://alpha.hornet.hive5.io";
		public static string Version 		= "v5";

        /// <summary>
        /// 중복호출로 단정하지 않는 시간 차이
        /// 순수 서버프로시저 수행 타임아웃 + Http request/response에 대한 latency고려된 값(단위:ms)
        /// </summary>
        public static int DuplicationApiCallExpirationPeriod = 2500;
	}
}

